# Generated by Django 5.2.8 on 2025-11-23 09:36

import django.db.models.deletion
import pgvector.django.vector
from django.conf import settings
from django.contrib.postgres.operations import CreateExtension
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # Enable pgvector extension FIRST
        CreateExtension("vector"),
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('fecha_carga', models.DateTimeField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(help_text='Usuario que subió el documento', on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Documento',
                'verbose_name_plural': 'Documentos',
                'db_table': 'conflict_detector_documento',
                'ordering': ['-fecha_carga'],
            },
        ),
        migrations.CreateModel(
            name='DescubrimientoConflicto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proyecto_id', models.CharField(max_length=50)),
                ('proyecto_titulo', models.TextField()),
                ('max_nivel_relevancia', models.IntegerField(default=0, help_text='Nivel máximo de relevancia entre todos los impactos (0-100)')),
                ('descripcion_impacto_consolidada', models.TextField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('PENDING', 'Pendiente'), ('TRACKING', 'En Seguimiento'), ('DISCARDED', 'Descartado')], default='PENDING', help_text='Estado del descubrimiento: Pendiente, En Seguimiento o Descartado', max_length=20)),
                ('fecha_analisis', models.DateTimeField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('documento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='descubrimientos', to='conflict_detector.documento')),
            ],
            options={
                'verbose_name': 'Descubrimiento de Conflicto',
                'verbose_name_plural': 'Descubrimientos de Conflictos',
                'db_table': 'conflict_detector_descubrimiento_conflicto',
                'ordering': ['-fecha_analisis'],
            },
        ),
        migrations.CreateModel(
            name='EmbeddingCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_hash', models.CharField(db_index=True, help_text='Hash SHA256 del texto original', max_length=64, unique=True)),
                ('embedding', pgvector.django.vector.VectorField(dimensions=1536, help_text='Vector de embedding generado por OpenAI')),
                ('model_name', models.CharField(default='text-embedding-3-small', help_text='Nombre del modelo de embedding utilizado', max_length=100)),
                ('dimension', models.IntegerField(default=1536, help_text='Dimensión del vector de embedding')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Embedding Cache',
                'verbose_name_plural': 'Embedding Caches',
                'db_table': 'conflict_detector_embedding_cache',
                'indexes': [models.Index(fields=['text_hash', 'model_name'], name='conflict_de_text_ha_b7ab4f_idx')],
            },
        ),
        migrations.CreateModel(
            name='ImpactoDescubierto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('articulo_numero', models.IntegerField(help_text='Número del artículo de ley que genera el conflicto')),
                ('extracto_interno', models.TextField(help_text='Extracto del documento interno que presenta conflicto')),
                ('extracto_articulo', models.TextField(help_text='Extracto del artículo de ley que genera el conflicto')),
                ('nivel_relevancia', models.IntegerField(help_text='Nivel de relevancia del impacto (0-100)')),
                ('descripcion_impacto', models.TextField(help_text='Análisis técnico-legal del impacto')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('descubrimiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='impactos', to='conflict_detector.descubrimientoconflicto')),
            ],
            options={
                'verbose_name': 'Impacto Descubierto',
                'verbose_name_plural': 'Impactos Descubiertos',
                'db_table': 'conflict_detector_impacto_descubierto',
                'ordering': ['-nivel_relevancia'],
            },
        ),
    ]
