# Generated by Django 5.2.7 on 2025-10-13 15:26

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="LogGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Datetime the log group was created",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        help_text="The type of log group, which determines the expected properties",
                        max_length=50,
                    ),
                ),
                (
                    "reference_id",
                    models.CharField(
                        db_index=True,
                        help_text="An identifier that should be unique across the log group type",
                        max_length=255,
                    ),
                ),
                (
                    "properties",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="A dictionary of arbitrary key-values",
                    ),
                ),
            ],
            options={
                "ordering": ["-created"],
                "indexes": [
                    models.Index(
                        fields=["type", "reference_id"],
                        name="auditlog_lo_type_f7f752_idx",
                    ),
                    models.Index(
                        fields=["-created"], name="auditlog_lo_created_2d119c_idx"
                    ),
                ],
                "unique_together": {("type", "reference_id")},
            },
        ),
        migrations.CreateModel(
            name="LogEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "user",
                    models.CharField(
                        help_text="A string identifying the authenticated user that performed the action",
                        max_length=255,
                    ),
                ),
                (
                    "timestamp",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        help_text="The time at which the logged action occurred",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Textual description of the action for informative purposes",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        help_text="The type of log entry, which determines the expected properties",
                        max_length=50,
                    ),
                ),
                (
                    "properties",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="A dictionary of arbitrary key-values",
                    ),
                ),
                (
                    "log_group",
                    models.ForeignKey(
                        help_text="The log group this entry belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="log_entries",
                        to="auditlog.loggroup",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Log entries",
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(
                        fields=["-timestamp"], name="auditlog_lo_timesta_c1d9bd_idx"
                    ),
                    models.Index(fields=["user"], name="auditlog_lo_user_9a36e5_idx"),
                    models.Index(
                        fields=["log_group", "-timestamp"],
                        name="auditlog_lo_log_gro_dac8f1_idx",
                    ),
                ],
            },
        ),
    ]
