/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginCallbackRouteImport } from './routes/login-callback'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedTab3RouteImport } from './routes/_authenticated/tab3'
import { Route as AuthenticatedTab2RouteImport } from './routes/_authenticated/tab2'
import { Route as AuthenticatedProfileIndexRouteImport } from './routes/_authenticated/profile/index'

const LoginCallbackRoute = LoginCallbackRouteImport.update({
  id: '/login-callback',
  path: '/login-callback',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedTab3Route = AuthenticatedTab3RouteImport.update({
  id: '/tab3',
  path: '/tab3',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedTab2Route = AuthenticatedTab2RouteImport.update({
  id: '/tab2',
  path: '/tab2',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedProfileIndexRoute =
  AuthenticatedProfileIndexRouteImport.update({
    id: '/profile/',
    path: '/profile/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/login': typeof LoginRoute
  '/login-callback': typeof LoginCallbackRoute
  '/tab2': typeof AuthenticatedTab2Route
  '/tab3': typeof AuthenticatedTab3Route
  '/': typeof AuthenticatedIndexRoute
  '/profile': typeof AuthenticatedProfileIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/login-callback': typeof LoginCallbackRoute
  '/tab2': typeof AuthenticatedTab2Route
  '/tab3': typeof AuthenticatedTab3Route
  '/': typeof AuthenticatedIndexRoute
  '/profile': typeof AuthenticatedProfileIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/login-callback': typeof LoginCallbackRoute
  '/_authenticated/tab2': typeof AuthenticatedTab2Route
  '/_authenticated/tab3': typeof AuthenticatedTab3Route
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/profile/': typeof AuthenticatedProfileIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/login' | '/login-callback' | '/tab2' | '/tab3' | '/' | '/profile'
  fileRoutesByTo: FileRoutesByTo
  to: '/login' | '/login-callback' | '/tab2' | '/tab3' | '/' | '/profile'
  id:
    | '__root__'
    | '/_authenticated'
    | '/login'
    | '/login-callback'
    | '/_authenticated/tab2'
    | '/_authenticated/tab3'
    | '/_authenticated/'
    | '/_authenticated/profile/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
  LoginCallbackRoute: typeof LoginCallbackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login-callback': {
      id: '/login-callback'
      path: '/login-callback'
      fullPath: '/login-callback'
      preLoaderRoute: typeof LoginCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/tab3': {
      id: '/_authenticated/tab3'
      path: '/tab3'
      fullPath: '/tab3'
      preLoaderRoute: typeof AuthenticatedTab3RouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/tab2': {
      id: '/_authenticated/tab2'
      path: '/tab2'
      fullPath: '/tab2'
      preLoaderRoute: typeof AuthenticatedTab2RouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/profile/': {
      id: '/_authenticated/profile/'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedTab2Route: typeof AuthenticatedTab2Route
  AuthenticatedTab3Route: typeof AuthenticatedTab3Route
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedProfileIndexRoute: typeof AuthenticatedProfileIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedTab2Route: AuthenticatedTab2Route,
  AuthenticatedTab3Route: AuthenticatedTab3Route,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedProfileIndexRoute: AuthenticatedProfileIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
  LoginCallbackRoute: LoginCallbackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
